server.port=8080
server.address=0.0.0.0

# Thymeleaf configurations to avoid caching issues during development
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.web.resources.cache.period=0